language: ruby
rvm:
  - 1.8.7
  - 1.9.3
script:
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 2.6.0"
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.6.0"
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.6.0"
      gemfile: .gemfile
  allow_failures:
    - rvm: 1.8.7
      env: PUPPET_VERSION="~> 2.6.0"
      gemfile: .gemfile

gemfile: .gemfile
notifications:
  email:
    - al@lab42.it
