---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2
script: bundle exec rake test
env:
  - PUPPET_GEM_VERSION="~> 3.6.0"
  - PUPPET_GEM_VERSION="~> 3.7.0"
  - PUPPET_GEM_VERSION="~> 3.8.0"
  - PUPPET_GEM_VERSION="~> 4.0.0"
  - PUPPET_GEM_VERSION="~> 4.1.0"
matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.0.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 4.1.0"
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.6.0"
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.7.0"
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.8.0"
