fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    "staging": "git://github.com/voxpupuli/puppet-staging.git"
    "erlang:": "git://github.com/garethr/garethr-erlang.git"
  symlinks:
    "rabbitmq": "#{source_dir}"
