fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: 4.7.0
    sysctl:
      repo: "git://github.com/fiddyspence/puppet-sysctl.git"
      ref: 1.1.0
  symlinks:
    swap_file: "#{source_dir}"
