/**
 * Sanitize to-publish data by running it through a RESTful Bleach endpoint
 */
exports.bleachData = function(endpoint) {
  var sanitize = require("htmlsanitizer");
  // Whitelist for HTML5 elements
  var ALLOWED_TAGS = [
      "!doctype",
      "html",
      "body",
      "a",
      "abbr",
      "address",
      "area",
      "article",
      "aside",
      "audio",
      "b",
      "base",
      "bdi",
      "bdo",
      "blockquote",
      "body",
      "br",
      "button",
      "canvas",
      "caption",
      "cite",
      "code",
      "col",
      "colgroup",
      //"command",
      //"datalist",
      "dd",
      "del",
      "details",
      "dfn",
      "div",
      "dl",
      "dt",
      "em",
      //"embed",
      "fieldset",
      "figcaption",
      "figure",
      "footer",
      "form",
      "h1","h2","h3","h4","h5","h6",
      "head",
      "header",
      "hgroup",
      "hr",
      "html",
      "i",
      "iframe",
      "img",
      "input",
      "ins",
      "keygen",
      "kbd",
      "label",
      "legend",
      "li",
      "link",
      "map",
      "mark",
      "menu",
      "meta",
      "meter",
      "nav",
      //"noscript",
      //"object",
      "ol",
      "optgroup",
      "option",
      "output",
      "p",
      "param",
      "pre",
      "progress",
      "q",
      "rp",
      "rt",
      "s",
      "samp",
      //"script",
      "section",
      "select",
      "small",
      "source",
      "span",
      "strong",
      "style",
      "sub",
      "summary",
      "sup",
      "table",
      "tbody",
      "td",
      "textarea",
      "tfoot",
      "th",
      "thead",
      "time",
      "title",
      "tr",
      //"track",
      "u",
      "ul",
      "var",
      "video",
      "wbr"
  ];

  // Whitelist for HTML5 element attributes.
  var ALLOWED_ATTRS = {
    "*": ["class", "id", "lang", "style", "tabindex", "title", "disabled"],
    "a": ["href"],
    "audio": ["controls", "autoplay", "preload", "loop", "src"],
    "button": ["name", "type", "value"],
    "base": ["href"],
    "canvas": ["width", "height"],
    //"embed": ["height","src","type","width"],
    "iframe": ["src", "width", "height", "allowfullscreen"],
    "img": ["src", "width", "height", "alt"],
    "input": ["type","checked","min","max","maxlength","name","placeholder","pattern",
              "readonly","required","step","value"],
    "link": ["href", "rel", "type", "crossorigin", "media"],
    "menu": ["type", "label"],
    "meta": ["charset", "name", "content"],
    "meter": ["value","min","max","low","high","optimum"],
    //"object": ["data","height","width","name","type"],
    "optgroup": ["label"],
    "option": ["label", "selected", "value"],
    "output": ["for","name"],
    "param": ["name", "value"],
    "progress": ["max","value"],
    "q": ["cite"],
    "source": ["src","type","media"],
    //"script": ["type", "src"],
    "style": ["type","media","scoped"],
    "textarea": ["cols","name","maxlength","readonly","placeholder","required","rows",
                 "selectionDirection","selectionStart","selectionEnd","wrap"],
    "th": ["colspan","rowspan"],
    "td": ["rowspan"],
    "time": ["datetime","pubdate"],
    //"track": ["default","kind","label","src","srclang"],
    "video": ["controls", "autoplay", "preload", "loop", "mediaGroup", "src",
              "poster", "muted", "width", "height"]
  };

  // Whitelist for CSS properties
  var ALLOWED_STYLES = [
    "accelerator",
    "azimuth",
    "background",
    "background-attachment",
    "background-color",
    "background-image",
    "background-position",
    "background-position-x",
    "background-position-y",
    "background-repeat",
    "behavior",
    "border",
    "border-bottom",
    "border-bottom-color",
    "border-bottom-style",
    "border-bottom-width",
    "border-collapse",
    "border-color",
    "border-left",
    "border-left-color",
    "border-left-style",
    "border-left-width",
    "border-right",
    "border-right-color",
    "border-right-style",
    "border-right-width",
    "border-spacing",
    "border-style",
    "border-top",
    "border-top-color",
    "border-top-style",
    "border-top-width",
    "border-width",
    "bottom",
    "caption-side",
    "clear",
    "clip",
    "color",
    "content",
    "counter-increment",
    "counter-reset",
    "cue",
    "cue-after",
    "cue-before",
    "cursor",
    "direction",
    "display",
    "elevation",
    "empty-cells",
    "filter",
    "float",
    "font",
    "font-family",
    "font-size",
    "font-size-adjust",
    "font-stretch",
    "font-style",
    "font-variant",
    "font-weight",
    "height",
    "ime-mode",
    "include-source",
    "layer-background-color",
    "layer-background-image",
    "layout-flow",
    "layout-grid",
    "layout-grid-char",
    "layout-grid-char-spacing",
    "layout-grid-line",
    "layout-grid-mode",
    "layout-grid-type",
    "left",
    "letter-spacing",
    "line-break",
    "line-height",
    "list-style",
    "list-style-image",
    "list-style-position",
    "list-style-type",
    "margin",
    "margin-bottom",
    "margin-left",
    "margin-right",
    "margin-top",
    "marker-offset",
    "marks",
    "max-height",
    "max-width",
    "min-height",
    "min-width",
    "orphans",
    "outline",
    "outline-color",
    "outline-style",
    "outline-width",
    "overflow",
    "overflow-X",
    "overflow-Y",
    "padding",
    "padding-bottom",
    "padding-left",
    "padding-right",
    "padding-top",
    "page",
    "page-break-after",
    "page-break-before",
    "page-break-inside",
    "pause",
    "pause-after",
    "pause-before",
    "pitch",
    "pitch-range",
    "play-during",
    "position",
    "quotes-replace",
    "richness",
    "right",
    "ruby-align",
    "ruby-overhang",
    "ruby-position",
    "size",
    "speak",
    "speak-header",
    "speak-numeral",
    "speak-punctuation",
    "speech-rate",
    "stress",
    "scrollbar-arrow-color",
    "scrollbar-base-color",
    "scrollbar-dark-shadow-color",
    "scrollbar-face-color",
    "scrollbar-highlight-color",
    "scrollbar-shadow-color",
    "scrollbar-3d-light-color",
    "scrollbar-track-color",
    "table-layout",
    "text-align",
    "text-align-last",
    "text-decoration",
    "text-indent",
    "text-justify",
    "text-overflow",
    "text-shadow",
    "text-transform",
    "text-autospace",
    "text-kashida-space",
    "text-underline-position",
    "top",
    "unicode-bidi",
    "vertical-align",
    "visibility",
    "voice-family",
    "volume",
    "white-space",
    "widows",
    "width",
    "word-break",
    "word-spacing",
    "word-wrap",
    "writing-mode",
    "z-index",
    "zoom"
  ];

  // Sanitize some HTML code by running it through Bleach
  return function(req, res, next) {
    sanitize({
      endpoint: endpoint,
      text: req.body.html,
      tags: ALLOWED_TAGS,
      attributes: ALLOWED_ATTRS,
      styles: ALLOWED_STYLES,
      strip: false,
      strip_comments: false,
      parse_as_fragment: false
    }, function(err, sanitizedData) {
      req.body.sanitizedHTML = sanitizedData;
      next(err);
    });
  };
};
