---
branches:
  only:
    - master
language: ruby
bundler_args: --without development
script: bundle exec rake test
after_success:
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - .forge-releng/publish
rvm:
  - 1.8.7
  - 1.9.3
env:
  matrix:
    - PUPPET_GEM_VERSION="~> 2.7.0"
    - PUPPET_GEM_VERSION="~> 3.0.0"
    - PUPPET_GEM_VERSION="~> 3.1.0"
    - PUPPET_GEM_VERSION="~> 3.2.0"
    - PUPPET_GEM_VERSION="~> 3.3.0"
    - PUPPET_GEM_VERSION="~> 3.4.0"
  global:
  - PUBLISHER_LOGIN=saz
  - secure: |-
      XYhK2TXSAjVeXWONjNpxKrKA6ogF5kazF/81eP5i0FzRoXUI+yemSYsrlA8oIRZjL6qrfCIT
      UYKBYeySBrJ4qM9K36mTiqOx1VuevAuM8GRTy4h52lx0MHa/puFvHwKbMbjkBVurhyyZg8mL
      cAtGs+KU2/oehrdBgyVfgQ08M9E=
matrix:
  include:
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.4.0"
notifications:
  email: false
