default_set: 'centos-64-x64'
sets:
  'centos-64-x64':
    nodes:
      "main.foo.vm":
        prefab: 'centos-64-x64'
  'debian-70rc1-x64':
    nodes:
      "main":
        prefab: 'debian-70rc1-x64'
