---
.travis.yml:
  includes:
  - rvm: 2.3.1
    env: PUPPET_GEM_VERSION="~> 4.0" STDLIB_LOG_DEPRECATIONS="false"
    bundler_args: --without system_tests
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STDLIB_LOG_DEPRECATIONS="false"
    bundler_args: --without system_tests
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
    bundler_args: --without system_tests
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
    bundler_args: --without system_tests
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
    bundler_args: --without system_tests
Rakefile:
  extra_disabled_lint_checks:
  - 'disable_only_variable_string'
spec/spec_helper.rb:
  allow_deprecations: true
